version: '3.9'

services:
  eventnotifier:
    image: ${DOCKER_REGISTRY-}eventnotifier
    build:
      context: .
      dockerfile: EventNotifier/Dockerfile
    environment:
        - ConnectionStrings__RedisConnection=redis
        - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=EventNotifier;User Id=postgres;Password=QWEewq1010; #Extract to .env file later
    depends_on:
        - db
        - redis
    networks:
        - backend

    ports:
        - "8080:80"
  db:
    container_name: db
    restart: always
    build:
        dockerfile: Postgres/Dockerfile
    volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./Postgres/postgis_init.sql:/docker-entrypoint-initdb.d/postgis_init.sql
    networks: 
        - backend
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=QWEewq1010
        - POSTGRES_DB=EventNotifier
  redis:
    image: redis
    volumes:
    - redis_data:/data
    ports:
        - "6379:6379"
    networks:
        - backend



networks:
  backend:
    driver: bridge
volumes:
    redis_data:
    postgres_data: