version: '3.9'

services:
  eventnotifier:
    image: ${DOCKER_REGISTRY-}eventnotifier
    build:
      context: .
      dockerfile: EventNotifier/Dockerfile
    environment:
        - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=EventNotifier;User Id=postgres;Password=QWEewq1010;
    depends_on:
        - db
    networks:
        - backend
    links:
        - db
    ports:
        - "8080:80"
  db:
    container_name: db
    restart: always
    image: postgres:latest
    networks: 
        - backend
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=QWEewq1010
        - POSTGRES_DB=EventNotifier



networks:
  backend:
    driver: bridge
