version: '3.9'

services:
  eventnotifier:
    image: ${DOCKER_REGISTRY-}eventnotifier
    build:
      context: .
      dockerfile: EventNotifier/Dockerfile
    environment:
        - ConnectionStrings__RedisConnection=redis
        - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=${POSTGRES_DB};User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}; 
    depends_on:
        - db
        - redis
    networks:
        - backend

    ports:
        - "5146:80"
  db:
    container_name: db
    restart: always
    build:
        dockerfile: Postgres/Dockerfile
    volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./Postgres/postgis_init.sql:/docker-entrypoint-initdb.d/postgis_init.sql
    networks: 
        - backend
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
  redis:
    image: redis
    volumes:
    - redis_data:/data
    ports:
        - "6379:6379"
    networks:
        - backend



networks:
  backend:
    driver: bridge
volumes:
    redis_data:
    postgres_data: